# Contenedor apache con php
version: '3.1'
services:
  wordpress:
    container_name: dam2_wordpressFuente
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: apache
        WORDPRESS_DB_PASSWORD: apache
        WORDPRESS_DB_NAME: mysql_apache
  db:
    container_name: dam2_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: apache
      MYSQL_PASSWORD: apache
      MYSQL_DATABASE: mysql_apache